development:
    adapter: mysql2
    encoding: utf8
    pool: 5
    database: phylator_development
    username: root
    password: 0402Jonas
    port: 3306

test:
    adapter: mysql2
    encoding: utf8
    pool: 5
    database: phylator_test
    username: root
    password: 0402Jonas
    port: 3306
