stripe:
    publishable_key: pk_test_eOpXmFh05CQjWwo87etVRjbc
    secret_key: sk_test_Yo26npXx57sxVukeGQ0zshWx

algoliasearch:
    application_id: BELGHUUECR
    api_key: 3ead4a057c74d82e87a67abac9342eb1
    search_key: 129450ba7709f82016843156552e66db
sentry_raven:
    dsn: 'https://2925cce1cec0488fa1ebae95bfb147eb:c51669cfaf3f4e3ea6d1b95ffe4a2bcc@sentry.io/260645'
